source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Sauron' do
platform :ios, '16.0'
pod 'mqttc/MinL', :git => 'https://github.com/ckrey/mqttc.git'

pod 'ABStaticTableViewController', :git => 'https://github.com/k06a/ABStaticTableViewController.git'
pod 'CocoaLumberjack'
pod 'DSJSONSchemaValidation'
#pod 'libsodium'
pod 'Sodium'
pod 'AppAuth'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end

